version: '3.8'
services:
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    container_name: user
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  post:
    build:
      context: .
      dockerfile: ./apps/post/Dockerfile
      target: development
    command: npm run start:dev post
    env_file:
      - .env.production
    ports:
      - "3001:3001"
    container_name: post
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq  
    restart: unless-stopped

  comment:
    build:
      context: .
      dockerfile: ./apps/comment/Dockerfile
      target: development
    command: npm run start:dev comment
    env_file:
      - .env.production
    ports:
      - "3002:3002"
    container_name: comment
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  bookmark:
    build:
      context: .
      dockerfile: ./apps/bookmark/Dockerfile
      target: development
    command: npm run start:dev bookmark
    env_file:
      - .env.production
    container_name: bookmark
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  
  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: npm run start:dev notification
    env_file:
      - .env.production
    container_name: notification
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: microserviceblog
    ports:
      - '5432:5432'
    env_file:
      - .env.production
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: redis
    env_file:
      - .env.production
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: rabbitmq
    container_name: rabbitmq
    env_file:
      - .env.production
    restart: unless-stopped

  nginx-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - user
      - post
      - comment
      - bookmark
      - notification
    ports:
        - '8080:8080'
    env_file:
      - .env.production
    container_name: nginx-proxy
    restart: unless-stopped

volumes:
  postgres_data:

